steps:
- name: 'gcr.io/cloud-builders/git'
  id: clone-dcm4che
  args:
  - clone
  - https://github.com/dcm4che/dcm4che.git
  - dcm4che

- name: 'gcr.io/cloud-builders/git'
  id: checkout-dcm4che-tag
  args:
  - checkout
  - "tags/5.15.1"
  dir: dcm4che

- name: ${_MAVEN_IMAGE}
  id: build-tools
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - bash
  - integration_test/mvn-install-tools.sh

- name: ${_MAVEN_IMAGE}
  id: store-scp
  args:
  - bash
  - integration_test/run-store-scp-and-wait.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  - ${_CLOSE_STORE_SCP_PORT}

- name: ${_GRADLE_IMAGE}
  id: adapter-build
  args: [ 'bash', './integration_test/build-adapters.sh', '${_IMAGEPROJECT}', '${SHORT_SHA}']
  waitFor: ['-']

# run adapter

- name: 'gcr.io/${_IMAGEPROJECT}/healthcare-api-dicom-dicomweb-adapter-import:${SHORT_SHA}'
  id: adapter-main
  entrypoint: 'bash'
  args: [ '-c',
          "/import/bin/import --dimse_aet=IMPORTADAPTER --dimse_port=${_ADAPTER_PORT} --dicomweb_address=https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb --aet_dictionary_inline=\"[{\"name\":\"STORESCP\",\"host\":${_STORE_SCP_RUN_STEP},\"port\":${_STORE_SCP_PORT}},{\"name\":\"STGCMTSCU\",\"host\":${_COMMITMENT_SCU_STEP},\"port\":${_COMMITMENT_SCU_PORT}},]\" --verbose & trap \"exit 0\" SIGTERM; while true; do sleep 1; done"]
  waitFor: ['adapter-build']

# create dataset if not exists, re-create store (delete if exists, then create)
- name: 'google/cloud-sdk:250.0.0'
  id: setup-dataset-and-dicom-store
  args:
  - bash
  - integration_test/setup-dataset-and-store.sh
  - ${_PROJECT}
  - ${_LOCATION}
  - ${_DATASET}
  - ${_STORE_NAME}
  waitFor: ['-']

# busybox is a compact utility image
- name: 'busybox:latest'
  id: wait-for-adapter
  args:
  - ash
  - integration_test/wait-for-port.sh
  - ${_ADAPTER_RUN_STEP}
  - ${_ADAPTER_PORT}
  timeout: 5m
  waitFor:
  - build-tools
  - adapter-build
  - setup-dataset-and-dicom-store

- name: 'busybox:latest'
  id: wait-for-storescp
  args:
  - ash
  - integration_test/wait-for-port.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  timeout: 5m
  waitFor:
  - build-tools

- name: ${_MAVEN_IMAGE}
  id: run-store-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.storescu.StoreSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} ../../../integration_test/example.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"
  waitFor:
  - wait-for-adapter

- name: ${_MAVEN_IMAGE}
  id: run-find-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.findscu.FindSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -L IMAGE -X --out-cat --out-file findscu-result.xml --out-dir ../../../integration_test/'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-findscu"
  waitFor:
  - run-store-scu

# Stgcmtscu  waits for n-event-report after n-action request returns success,
# if it doesn't get one within cloud build step timeout of 30 seconds, step fails.
- name: ${_MAVEN_IMAGE}
  id: run-commitment-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.stgcmtscu.StgCmtSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -b STGCMTSCU:${_COMMITMENT_SCU_PORT} --explicit-vr --directory /workspace/integration_test/commitment_result /workspace/integration_test/example.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-stgcmtscu"
  waitFor:
  - run-find-scu
  timeout: 30s

- name: ${_MAVEN_IMAGE}
  id: run-move-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.movescu.MoveSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -m SOPInstanceUID=111 --dest STORESCP'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-movescu"
  waitFor:
  - run-commitment-scu
  - wait-for-storescp

- name: 'gcr.io/cloud-builders/docker'
  id:  close-adapter
  entrypoint: bash
  args:
      - './integration_test/stop-image.sh'
      - '${_IMAGEPROJECT}'
      - '${SHORT_SHA}'
  waitFor: ['run-move-scu']

- name: 'busybox:latest'
  id: close-store-scp
  args:
  - nc
  - '-z'
  - ${_STORE_SCP_RUN_STEP}
  - ${_CLOSE_STORE_SCP_PORT}
  waitFor:
  - run-move-scu

- name: 'google/cloud-sdk:250.0.0'
  id: check-store-curl
  args:
  - bash
  - integration_test/curl-dcm.sh
  - "https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb/studies/111/series/111/instances/111"
  - integration_test/downloaded.dcm
  waitFor:
  - run-store-scu

- name: 'busybox:latest'
  id: check-store-diff
  args:
  - diff
  - 'integration_test/downloaded.dcm'
  - 'integration_test/example.dcm'
  waitFor:
  - check-store-curl

- name: 'busybox:latest'
  id: check-find-diff
  args:
  - diff
  - 'integration_test/findscu-result1.xml'
  - 'integration_test/findscu-expected.xml'
  waitFor:
  - run-find-scu

# storescp adds 1 extra tag
# (0002,0016) [AE] SourceApplicationEntityTitle: IMPORTADAPTER
- name: 'busybox:latest'
  id: check-move-diff
  args:
  - diff
  - 'integration_test/storescp-data/111'
  - 'integration_test/example-moved.dcm'
  waitFor:
  - run-move-scu

- name: ${_MAVEN_IMAGE}
  id: check-commitment-diff
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - bash
  - /workspace/integration_test/diff-commitment-result.sh
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-dcm2xml"
  waitFor:
  - run-commitment-scu

- name: 'google/cloud-sdk:250.0.0'
  id: delete-dicom-store
  args:
  - gcloud
  - alpha
  - healthcare
  - dicom-stores
  - delete
  - ${_STORE_NAME}
  - "--project=${_PROJECT}"
  - "--dataset=${_DATASET}"
  - "--location=${_LOCATION}"
  - "--quiet"
  waitFor:
  - check-store-curl
  - run-find-scu
  - run-move-scu
  - run-commitment-scu

- name: 'google/cloud-sdk:250.0.0'
  id: publish-image
  args: [ 'bash', 'integration_test/publish-images.sh', '${_IMAGEPROJECT}', "${_PUBLISH}"]
  waitFor: ['delete-dicom-store']
timeout: 1800s
substitutions:
  _VERSION: v1beta1
  _PROJECT: gcp-healthcare-oss-test
  _IMAGEPROJECT: cloud-healthcare-containers
  _LOCATION: us-central1
  _DATASET: healthcare-dicom-dicomweb-adapter-test
  _STORE_NAME: integration-test-store
  _ADAPTER_PORT: '2575'
  _STORE_SCP_PORT: '2576'
  _CLOSE_STORE_SCP_PORT: '3001'
  _COMMITMENT_SCU_PORT: '4000'
# Cloud build names containers that run steps: step_0, step_1 etc. These are also their dns names on docker network.
# Update to correct value if adding/removing steps before adapter run.
  _ADAPTER_RUN_STEP: 'step_5'
  _STORE_SCP_RUN_STEP: 'step_3'
  _COMMITMENT_SCU_STEP: 'step_11'
  _GRADLE_IMAGE: 'gradle:5.6-jdk11'
  _MAVEN_IMAGE: 'maven:3.6-jdk-11'
  _PUBLISH: 'false'