steps:
- name: 'gcr.io/cloud-builders/git'
  id: clone-dcm4che
  args:
  - clone
  - https://github.com/dcm4che/dcm4che.git
  - dcm4che

- name: 'gcr.io/cloud-builders/git'
  id: checkout-dcm4che-tag
  args:
  - checkout
  - "tags/5.15.1"
  dir: dcm4che

- name: ${_MAVEN_IMAGE}
  id: build-tools
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - bash
  - integration_test/scripts/mvn-install-tools.sh

- name: ${_MAVEN_IMAGE}
  id: store-scp
  args:
  - bash
  - integration_test/scripts/run-store-scp-and-wait.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  - ${_CLOSE_STORE_SCP_PORT}

- name: ${_GRADLE_IMAGE}
  id: adapter-build
  args: [ 'bash', './integration_test/scripts/build-adapters.sh', '${_IMAGEPROJECT}', '${SHORT_SHA}']
  waitFor: ['-']

# run adapter

- name: 'gcr.io/${_IMAGEPROJECT}/healthcare-api-dicom-dicomweb-adapter-import:${SHORT_SHA}'
  id: adapter-main
  entrypoint: 'bash'
  args: [ '-c',
          "/import/bin/import \
          --dimse_aet=IMPORTADAPTER \
          --dimse_port=${_ADAPTER_PORT} \
          --dicomweb_address=https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb \
          --monitoring_project_id=${_PROJECT} \
          --aet_dictionary_inline=\"[{\\\"name\\\":\\\"STORESCP\\\",\\\"host\\\":${_STORE_SCP_RUN_STEP},\\\"port\\\":${_STORE_SCP_PORT}},{\\\"name\\\":\\\"STGCMTSCU\\\",\\\"host\\\":${_COMMITMENT_SCU_STEP},\\\"port\\\":${_COMMITMENT_SCU_PORT}},]\" \
          --destination_config_inline=\"[{\\\"filter\\\":\\\"Modality=MG\\\",\\\"dicomweb_destination\\\":\\\"https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}-destination-2/dicomWeb\\\"}]\" \
          --redact_remove_list=ContentTime,ContentDate \
          --store_compress_to_transfer_syntax=1.2.840.10008.1.2.4.90 \
          --verbose & trap \"exit 0\" SIGTERM; while true; do sleep 1; done"]
  waitFor: ['adapter-build']

# create dataset if not exists, re-create store (delete if exists, then create)
- name: ${_CLOUD_SDK_IMAGE}
  id: setup-dataset-and-dicom-store
  args:
  - bash
  - integration_test/scripts/setup-dataset-and-store.sh
  - ${_PROJECT}
  - ${_LOCATION}
  - ${_DATASET}
  - ${_STORE_NAME}
  waitFor: ['-']

# busybox is a compact utility image
- name: 'busybox:latest'
  id: wait-for-adapter
  args:
  - ash
  - integration_test/scripts/wait-for-port.sh
  - ${_ADAPTER_RUN_STEP}
  - ${_ADAPTER_PORT}
  timeout: 5m
  waitFor:
  - build-tools
  - adapter-build
  - setup-dataset-and-dicom-store

- name: 'busybox:latest'
  id: wait-for-storescp
  args:
  - ash
  - integration_test/scripts/wait-for-port.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  timeout: 5m
  waitFor:
  - build-tools

- name: ${_MAVEN_IMAGE}
  id: run-store-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.storescu.StoreSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} ../../../integration_test/data/example.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"
  waitFor:
  - wait-for-adapter

- name: ${_MAVEN_IMAGE}
  id: run-store-scu-destination-2
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.storescu.StoreSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} ../../../integration_test/data/example-mg.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"
  waitFor:
  - wait-for-adapter

- name: ${_MAVEN_IMAGE}
  id: run-find-scu-instance
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.findscu.FindSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -L IMAGE -X --out-cat --out-file findscu-instance-result.xml --out-dir ../../../integration_test/'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-findscu"
  waitFor:
  - run-store-scu

- name: ${_MAVEN_IMAGE}
  id: run-find-scu-series
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.findscu.FindSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -L SERIES -X --out-cat --out-file findscu-series-result.xml --out-dir ../../../integration_test/'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-findscu"
  waitFor:
  - run-store-scu

- name: ${_MAVEN_IMAGE}
  id: run-find-scu-study
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.findscu.FindSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -L STUDY -X --out-cat --out-file findscu-study-result.xml --out-dir ../../../integration_test/'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-findscu"
  waitFor:
  - run-store-scu

- name: ${_MAVEN_IMAGE}
  id: run-move-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.movescu.MoveSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -m SOPInstanceUID=${_REPLACED_UID} --dest STORESCP'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-movescu"
  waitFor:
  - run-store-scu
  - wait-for-storescp

# Stgcmtscu  waits for n-event-report after n-action request returns success,
# if it doesn't get one within cloud build step timeout of 30 seconds, step fails.
# Run it after other tools to avoid timeout due to parallel execution.
- name: ${_MAVEN_IMAGE}
  id: run-commitment-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - '-ntp'
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.stgcmtscu.StgCmtSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -b STGCMTSCU:${_COMMITMENT_SCU_PORT} --explicit-vr --directory /workspace/integration_test/commitment_result /workspace/integration_test/data/example-redacted-jp2k.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-stgcmtscu"
  waitFor:
  - run-store-scu
  - run-store-scu-destination-2
  - run-find-scu-instance
  - run-find-scu-series
  - run-find-scu-study
  - run-move-scu
  timeout: 30s

- name: 'gcr.io/cloud-builders/docker'
  id:  close-adapter
  entrypoint: bash
  args:
      - './integration_test/scripts/stop-image.sh'
      - '${_IMAGEPROJECT}'
      - '${SHORT_SHA}'
  waitFor:
  - run-store-scu
  - run-store-scu-destination-2
  - run-find-scu-instance
  - run-find-scu-series
  - run-find-scu-study
  - run-move-scu
  - run-commitment-scu

- name: 'busybox:latest'
  id: close-store-scp
  args:
  - nc
  - '-z'
  - ${_STORE_SCP_RUN_STEP}
  - ${_CLOSE_STORE_SCP_PORT}
  waitFor:
  - run-move-scu

- name: ${_CLOUD_SDK_IMAGE}
  id: check-store-curl
  args:
  - bash
  - integration_test/scripts/curl-dcm.sh
  - "https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb/studies/${_REPLACED_UID}/series/${_REPLACED_UID}/instances/${_REPLACED_UID}"
  - integration_test/downloaded.dcm
  waitFor:
  - run-store-scu

# example-redacted has replaced UIDs and removed ContentTime,ContentDate tags
- name: 'busybox:latest'
  id: check-store-diff
  args:
  - diff
  - 'integration_test/downloaded.dcm'
  - 'integration_test/data/example-redacted-jp2k.dcm'
  waitFor:
  - check-store-curl

- name: ${_CLOUD_SDK_IMAGE}
  id: check-store-curl-destination-2
  args:
  - bash
  - integration_test/scripts/curl-dcm.sh
  - "https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}-destination-2/dicomWeb/studies/${_REPLACED_UID}/series/${_REPLACED_UID}/instances/${_REPLACED_UID}"
  - integration_test/downloaded-destination-2.dcm
  waitFor:
  - run-store-scu-destination-2

# example-redacted has replaced UIDs and removed ContentTime,ContentDate tags
- name: 'busybox:latest'
  id: check-store-diff-destination-2
  args:
  - diff
  - 'integration_test/downloaded-destination-2.dcm'
  - 'integration_test/data/example-redacted-mg-jp2k.dcm'
  waitFor:
  - check-store-curl-destination-2

- name: 'busybox:latest'
  id: check-find-diff-instance
  args:
  - diff
  - 'integration_test/findscu-instance-result1.xml'
  - 'integration_test/data/findscu-instance-expected.xml'
  waitFor:
  - run-find-scu-instance

- name: 'busybox:latest'
  id: check-find-diff-series
  args:
  - diff
  - 'integration_test/findscu-series-result1.xml'
  - 'integration_test/data/findscu-series-expected.xml'
  waitFor:
  - run-find-scu-series

- name: 'busybox:latest'
  id: check-find-diff-study
  args:
  - diff
  - 'integration_test/findscu-study-result1.xml'
  - 'integration_test/data/findscu-study-expected.xml'
  waitFor:
  - run-find-scu-study

# storescp adds 1 extra tag
# (0002,0016) [AE] SourceApplicationEntityTitle: IMPORTADAPTER
- name: 'busybox:latest'
  id: check-move-diff
  args:
  - diff
  - 'integration_test/storescp-data/${_REPLACED_UID}'
  - 'integration_test/data/example-redacted-moved-jp2k.dcm'
  waitFor:
  - run-move-scu

- name: ${_MAVEN_IMAGE}
  id: check-commitment-diff
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - bash
  - /workspace/integration_test/scripts/diff-commitment-result.sh
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-dcm2xml"
  waitFor:
  - run-commitment-scu

- name: ${_CLOUD_SDK_IMAGE}
  id: delete-dicom-store
  args:
  - gcloud
  - beta
  - healthcare
  - dicom-stores
  - delete
  - ${_STORE_NAME}
  - "--project=${_PROJECT}"
  - "--dataset=${_DATASET}"
  - "--location=${_LOCATION}"
  - "--quiet"
  waitFor:
  - check-store-curl
  - check-store-curl-destination-2
  - run-find-scu-instance
  - run-find-scu-series
  - run-find-scu-study
  - run-move-scu
  - run-commitment-scu

- name: ${_CLOUD_SDK_IMAGE}
  id: delete-dicom-store-destination-2
  args:
  - gcloud
  - beta
  - healthcare
  - dicom-stores
  - delete
  - "${_STORE_NAME}-destination-2"
  - "--project=${_PROJECT}"
  - "--dataset=${_DATASET}"
  - "--location=${_LOCATION}"
  - "--quiet"
  waitFor:
  - delete-dicom-store

- name: ${_CLOUD_SDK_IMAGE}
  id: publish-image
  args: [ 'bash', 'integration_test/scripts/publish-images.sh', '${_IMAGEPROJECT}', "${_PUBLISH}", "$REPO_NAME"]
  waitFor: ['delete-dicom-store']
  secretEnv: ['ACCESS_TOKEN']

timeout: 1800s
substitutions:
  _VERSION: v1beta1
  _PROJECT: gcp-healthcare-oss-test
  _IMAGEPROJECT: cloud-healthcare-containers
  _LOCATION: us-central1
  _DATASET: healthcare-dicom-dicomweb-adapter-test
  _STORE_NAME: integration-test-store
  _ADAPTER_PORT: '2575'
  _STORE_SCP_PORT: '2576'
  _CLOSE_STORE_SCP_PORT: '3001'
  _COMMITMENT_SCU_PORT: '4000'
# Cloud build names containers that run steps: step_0, step_1 etc. These are also their dns names on docker network.
# Update to correct value if adding/removing steps before adapter run.
  _ADAPTER_RUN_STEP: 'step_5'
  _STORE_SCP_RUN_STEP: 'step_3'
  _COMMITMENT_SCU_STEP: 'step_15'
# Deid redactor replaces Instance/Series/Study UIDs with pseudo-random value seeded from original.
# This value corresponds to '111'. UID replacement behavior is not configurable in redactor.
  _REPLACED_UID: '2.25.140302709094137852884202099990798014056'
  _GRADLE_IMAGE: 'gradle:5.6-jdk11'
  _MAVEN_IMAGE: 'maven:3.6-jdk-11'
  _CLOUD_SDK_IMAGE: 'google/cloud-sdk:272.0.0'
  _PUBLISH: 'false'
secrets:
- kmsKeyName: projects/gcp-healthcare-oss-test/locations/global/keyRings/default/cryptoKeys/github-robot-access-token
  secretEnv:
    ACCESS_TOKEN: CiQAM/SK3FUc1t+CnHDdgRzbc556FIyHddxRpsnolmSKfpiZ66sSUQDrEGO9gz15JIulryNagWzUOGbBEAaC04y85J8fNRjJZ8T8ntzh6Kt0Sa+GCG+3n5xSQdDJdj6xOG0LfVzvU+/K3mZ1KJlIcd0jiCeBrjYLlw==


